### ISSUE TITLE
When using in a Visual Studio extension it fails to load

### ISSUE THREAD

**Issue by timheuer** [samhocevar/emoji.wpf#72]
Sample repo: https://github.com/timheuer/VSIXProject7

Launch and then go to View...Other Windows...My Tool Window

I'm using in a Visual Studio extension and it is failing to load:

System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=Could not load file or assembly 'Emoji.Wpf, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at VSIXProject7.MyToolWindowControl.InitializeComponent() in D:\source\repos\VSIXProject7\VSIXProject7\ToolWindows\MyToolWindowControl.xaml:line 1

  This exception was originally thrown at this call stack:
    System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, ref System.Threading.StackCrawlMark, System.IntPtr, bool, bool, bool)
    System.Reflection.Assembly.Load(System.Reflection.AssemblyName)
    System.Windows.Baml2006.Baml2006SchemaContext.ResolveAssembly(System.Windows.Baml2006.Baml2006SchemaContext.BamlAssembly)
    System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlTypeToType(System.Windows.Baml2006.Baml2006SchemaContext.BamlType)
    System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(System.Windows.Baml2006.Baml2006SchemaContext.BamlType, short)
    System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(short)
    System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()
    System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
    System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
    System.Windows.Baml2006.Baml2006Reader.Read()
    ...
    [Call Stack Truncated]

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'Emoji.Wpf, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by timheuer** [comment]
Solving for others...in the VSPackage class for your extension adding this attribute:
```
[ProvideBindingPath]
```
